---
- name: "Install python3-pip"
  shell: python3 -m pip install --upgrade update
  become: yes

- name: "Install cron"
  apt:
    name: cron
  become: yes

- name: "Install ixnetwork-open-traffic-generator"
  pip: 
    name: ixnetwork-open-traffic-generator
  become: yes

- name: "add link to router"
  shell: ip route add 192.168.190.190 dev {{ansible_default_ipv4.alias}}
  become: yes

- name: "add route via router vm"
  shell: ip route add 192.168.190.0/24 via 192.168.190.190  dev {{ansible_default_ipv4.alias}}
  become: yes

- name: "add script that makes route persite"
  file: 
    src:  50-ifupdown.j2
    dest: etc/NetworkManager/dispatcher.d/50-ifupdown 
    mode: -x
  become: yes

- name: "copy traffic generator to host"
  file:
    src: traffic_gen.py
    dest: /home/master/traffic_gen.py
    mode: -x
  become: yes

- name: "Start cron job for traffic_gen"
  cron:
    name: "Fuzzed Random Traffic Generator"
    minute: "*/1"
    hour: "*"
    day: "*"
    month: "*"
    job: "python /home/master/traffic_gen.py 192.168.190.190 192.168.190.191 192.168.190.192 192.168.190.195"
  become: yes

- name: "Start cron job for illegal traffic_gen"
  cron:
    name: "Fuzzed Random Illegal Traffic Generator"
    minute: "*/3"
    hour: "*"
    day: "*"
    month: "*"
    job: "python /home/master/traffic_gen.py 192.168.190.194"
  become: yes