all:
  hosts:
    localhost:
     vars:
      ansible_connection: local


    #  ansible_connection: ssh
    #  ansible_user: "{{ ansible_user_name }}"
    #  ansible_ssh_pass: "{{ ansible_become_password }}"
