all:
  hosts:
  
    test:
        ansible_connection:  ssh
        ansible_user:       "{{ ansible_user_name }}"
        ansible_ssh_pass:   "{{ ansible_become_password }}"
        ansible_host:       "{{ansible_user_ip}}"
    
    
    #{{ansible_user_ip}}:

    # localhost:
    #  vars:
    #   #ansible_connection: local

  
    
