all:
  hosts:
  
    ansible_user_name:
        ansible_connection:  ssh
        ansible_user:       "{{ ansible_user_name }}"
        ansible_ssh_pass:   "{{ ansible_become_password }}"
        ansible_host:       "{{ansible_user_ip}}"
        ansible_python_interpreter: auto
    

  
    
