- name:  copy dummy-web-server.py to remote host
  copy:
    src: dummy-web-server.py
    dest: /opt/dummy-web-server.py
    mode: -x
  become: yes


- name: Copy service file to /etc/systemd/system
  template:
    src: dummy.service.j2
    dest: "/etc/systemd/system/dummy-webservice.service"
    mode: '755'
  become: yes


- name: reload service daemon
  command: systemctl daemon-reload
  become: yes

- name: Start dummy-webservice service
  service:
    name: "dummy-webservice"
    state: "started"
  become: yes