- name: Add Mongo packages repo
    apt_key: 
      id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5  
      keyserver: keyserver.ubuntu.com
- name: add repo itself
    apt_repository: 
      repo: 'deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.4 multiverse' 
      state: present                                      
- name: install mongodb
    apt: 
      pkg: mongodb-org 
      state: latest 
      update_cache: no
    notify:
    - start mongodb
